Feat/climsoft models
opencdms-dev/pyopencdms-old pull request #28
Opened 2021-09-08 22:19 UTC by Shaibujnr

https://github.com/opencdms/pyopencdms/issues/2

## TO EXECUTE DATABASE DDL For CLIMSOFT
`mysql -u root -p < script.sql`

## Execute the following statements to add primary key columns to the 24 core tables
```
alter table observationfinal add primary key (recordedFrom,describedBy,obsDatetime, obsLevel);
alter table observationinitial add primary key (recordedFrom,describedBy,obsDatetime,qcStatus,acquisitionType, obsLevel);
alter table instrumentinspection add primary key (performedOn, inspectionDatetime);
alter table faultresolution add primary key (resolvedDatetime, associatedWith);
alter table stationelement add primary key (recordedFrom, describedBy, recordedWith, beginDate);
alter table stationlocationhistory add primary key (belongsTo, openingDatetime);
alter table stationqualifier add primary key (qualifier, qualifierBeginDate, qualifierEndDate, belongsTo);
alter table observationschedule add primary key (classifiedInto, startTime, endTime);
alter table physicalfeature add primary key (associatedWith, beginDate, classifiedInto, description);
alter table featuregeographicalposition add primary key (belongsTo, observedOn);
alter table paperarchive add primary key (belongsTo, formDatetime, classifiedInto);
```

##  GENERATE MODELS
```
sqlacodegen "mysql://root:{{password}}@localhost/mariadb_climsoft_db_v4" --outfile opencdms/models/climsoft/v4_1_1_core.py --tables=observationfinal,observationinitial,station,obselement,instrument,instrumentfaultreport,instrumentinspection,faultresolution,stationelement,stationlocationhistory,stationqualifier,observationschedule,obsscheduleclass,physicalfeature,physicalfeatureclass,featuregeographicalposition,synopfeature,paperarchive,flags,acquisitiontype,qctype,qcstatusdefinition,regkeys,data_forms
```

2021-09-09 19:01 UTC, faysal-ishtiaq commented
I have gone through the PR and it looks good. However, when I followed the same process, there were some dissimilarities in the resultant file. So, I pushed a commit so that we can view the diff. Here is the commit 

https://github.com/opencdms/pyopencdms/commit/1ad710ef35af9b515e9c28d08ad2481d2481e168

Feel free to revert the commit

2021-09-09 19:03 UTC, faysal-ishtiaq commented on opencdms/models/climsoft/v4_1_1_core.py
> +# coding: utf-8
This file is the result of sqlacodegen run on my machine. I used latest mysql docker image. feel free to revert the commit if necessary. here is the commit https://github.com/opencdms/pyopencdms/commit/1ad710ef35af9b515e9c28d08ad2481d2481e168

2021-09-09 19:05 UTC, faysal-ishtiaq reviewed
LGTM. just let me know about the difference in this file  opencdms/models/climsoft/v4_1_1_core.py. See this commit https://github.com/opencdms/pyopencdms/commit/1ad710ef35af9b515e9c28d08ad2481d2481e168 to see the diff

2021-09-09 19:47 UTC, isedwards commented
Thank you @faysal-ishtiaq - these are all of the known changes that @Shaibujnr has made manually in order to make the models match the output of `alembic revision --autogenerate` (see the comments from list item 4 onwards [here](https://github.com/opencdms/pyopencdms/issues/2#issuecomment-909061505)).

This is mainly necessary so that SQLAlchemy's doesn't detect a difference and suggest a migration.

Could you revert 1ad710e for us and then I'll merge?

2021-09-09 19:52 UTC, faysal-ishtiaq commented
> Thank you @faysal-ishtiaq - these are all of the known changes that @Shaibujnr has made manually in order to make the models match the output of `alembic revision --autogenerate` (see the comments from list item 4 onwards [here](https://github.com/opencdms/pyopencdms/issues/2#issuecomment-909061505)).
> 
> This is mainly necessary so that SQLAlchemy's doesn't detect a difference and suggest a migration.
> 
> Could you revert [1ad710e](https://github.com/opencdms/pyopencdms/commit/1ad710ef35af9b515e9c28d08ad2481d2481e168) for us and then I'll merge?

reverted just now

2021-09-09 19:52 UTC, faysal-ishtiaq approved these changes

2021-09-10 09:12 UTC, isedwards requested changes

2021-09-10 09:12 UTC, isedwards commented on .gitignore
> +shaibu-activity.log
@faysal-ishtiaq could you remove this for now?
@Shaibujnr - would it be useful to include `*-activity.log` in a future commit? Is this a common file generated by the IDE (or possibly related to upwork?)

2021-09-10 09:12 UTC, isedwards commented on opencdms/models/__init__.py
>  # TODO remove and use automated tests instead.
@faysal-ishtiaq - could you remove this section to the end of the file and propose tests for both clide and climsoft using sqlite instead?

The clide code that was here imported `CLIDE_VIEWS` (`from opencdms.models.clide import metadata, CLIDE_VIEWS`) and used this to exclude these views/tables from the `get_schema_diff()` output.

The new version, that replaces the original clide example, can be turned into a test for climsoft.

2021-09-11 07:08 UTC, isedwards approved these changes

2021-09-11 07:22 UTC, merged