Addition of climate data model.
opencdms-dev/pyopencdms-old pull request #94
Opened 2023-01-27 16:58 UTC by david-i-berry

- Addition of v0.1 of climate data model (CDM)
- Addition or ORM for CDM.

2023-01-28 17:01 UTC, isedwards requested changes
I'm made most of the changes that I've added as comments here, but there are a couple of things I still need to check before changing.

I'll push an update later today.

2023-01-28 17:01 UTC, isedwards commented on opencdms/models/cdm.py
> +        "link": "Link to definition of observation type"  # noqa
Instead of worrying about discussing code formatting, I've [raised an issue](https://github.com/opencdms/pyopencdms/issues/96) to consider using the Black auto code formatter.

Here it would add a trailing comma (and also we wouldn't need to use `# noqa` comments as much)

2023-01-28 17:01 UTC, isedwards commented on opencdms/models/cdm.py
> +        super().__init__()  # noqa
I was wrong... it's not possible to use `super()` to call the `__init__` method that would have been added by the `@dataclass` decorator.

Our `def __init__()` here is just overwriting the decorator's `__init__` (because the decorator adds the method by assignment not by inheritance). The result is that none of the attributes (id, name etc.) are currently being added to the instance.

There are ways to implement optional arguments in data classes - but I think that the fix in this case is recognising that `link` is not completely optional... It is a field that will always exist in the database table but the database field can have a default value of empty string or `NULL`. 

Here's an example of moving away from having to define our own `__init__` to using `dataclasses.field` to specify a default value and thus make the argument optional. Note we can only do this if optional arguments are grouped at the end of the argument list.
```
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class ObservationType:
    id: int
    name: str
    description: str
    link: Optional[str] = field(default="")
```

Below is the result of the example code. `__init__` and `__repr__` have been implemented for us by the `@dataclass` decorator and are used by the example to instantiate instances of the class and print a representation:
```
>>> obs_type_a = ObservationType(1, 'myobstype', 'My Obs Type')
>>> obs_type_b = ObservationType(1, 'myobstype', 'My Obs Type', 'https')
>>> obs_type_a
ObservationType2(id=1, name='myobstype', description='My Obs Type', link='')
>>> obs_type_b
ObservationType2(id=1, name='myobstype', description='My Obs Type', link='https')
```

2023-01-28 17:01 UTC, isedwards commented on opencdms/provider/opencdmsdb/__init__.py
> +from geoalchemy2 import Geography
In this PR we should add `geoalchemy2` as a requirement in `/requirements.txt`

2023-01-28 17:01 UTC, isedwards commented on opencdms/provider/opencdmsdb/__init__.py
> +mapper_registry.map_imperatively(ObservationType, observation_type)
The domain model class need to be prefixed with the `cdm` module (also applies to other model classes below):
```
cdm.ObservationType
```

2023-01-28 17:01 UTC, isedwards commented on opencdms/provider/opencdmsdb/__init__.py
> +from sqlalchemy.orm import registry
We also need to import `relationship`:
```
from sqlalchemy.orm import registry, relationship
```

2023-01-28 17:01 UTC, isedwards commented on opencdms/models/cdm.py
> +class RecordStatu:
Typo, missing `s` on Status

2023-01-28 17:01 UTC, isedwards commented on opencdms/models/cdm.py
> +    def __init__(self, id: str, name: str, description: Optional[str], link: Optional[str], location: Optional[Geography], elevation: Optional[float], wigos_station_identifier: Optional[str], facilit
Should `date_established: Optional[str]` have type `date` / `datetime` instead?

2023-01-28 17:01 UTC, isedwards commented on opencdms/models/cdm.py
> +        "link": "Link to definition of feature type"  # noqa
In the future we'll populate the table comments automatically from the comments here in the domain models. When we do this, we should decide whether to automatically append `" (optional)"` to fields that are not required.

2023-01-28 17:01 UTC, isedwards commented on opencdms/models/cdm.py
> +    def table_info(self) -> str:
The `table_info` and `column_info` methods are repeated multiple times and should be refactored into a superclass.
See https://code-smells.com/dispensables/duplicate-code

2023-01-28 17:01 UTC, isedwards commented on opencdms/models/cdm.py
> +    def __init__(self, id: int, short_name: str, standard_name: Optional[str], units: str, description: str, link: Optional[str]):  # noqa
If we want `standard_name: Optional[str]` to be fully optional, in the sense that the class can be instantiated using positional arguments without specifying a standard name (e.g. `ObservedProperty(1, 'name', 'unit', 'desc'`), then the `standard_name` argument would have to come at the end with other optional arguments and be given a default value like `""` or `None`.

2023-01-28 22:37 UTC, chinedu117 commented on opencdms/models/cdm.py
> +        super().__init__()  # noqa
Yes. Also i think it would be nice to make all the fields optional, particularly the id field since it would be autogenerated by the database. Also since the corresponding columns for the fields in the database are nullable, we can make them None by default. 

See below:

```
from dataclasses import dataclass, field

@dataclass
class ObservationType:
    id: int = field(default=None)
    name: str = field(default=None)
    description: str = field(default=None)
    link: str  = field(default=None)


obs1 = ObservationType(name="DSD",description="SDSD")
obs2 = ObservationType(id=1,name="DSD",description="SDSD")

@dataclass
class Feature:
    id: int 
    name: str 
    description: str 
    link: str  = field(default="")


fe = Feature(name="Feature", description="description")



if __name__ == "__main__":
    print(obs1) 
    # ObservationType(id=None, name='DSD', description='SDSD', link=None)
    print(obs2)
    # ObservationType(id=1, name='DSD', description='SDSD', link=None)
    print(fe)
#     Traceback (most recent call last):
#   File "/home/chinedu/opencdms/test.py", line 23, in <module>
#     fe = Feature(name="Feature", description="description")
# TypeError: Feature.__init__() missing 1 required positional argument: 'id'
```

Attempting to initialize the Feature() class without defining an id or any of the fields would error out.
Except this is an intended behaviour, we could make them all optional by defining them as NoneType.

2023-01-29 15:02 UTC, isedwards commented on opencdms/models/cdm.py
> +        super().__init__()  # noqa
Thank you @chinedu117 - I definitely agree with the surrogate `id` being optional for the reasons you've given.

For the other fields I think the business rules should determine their optionality. If it is always the case that a `Host` object anywhere in the system must have a `name` and `location` in order to exist - is there any situation were we may want an empty `Host` object (that isn't following the business rules)?

2023-01-29 17:35 UTC, chinedu117 commented on opencdms/models/cdm.py
> +        super().__init__()  # noqa
I agree with you. It doesnt make sense to have an all NULL row.

2023-02-01 15:39 UTC, merged